### ISSUE TITLE
Ripple testnet server returns 403 Forbidden in Microsoft Edge browser

### ISSUE THREAD

**Issue by matejr** [XRPLF/xrpl-dev-portal#203] opened 2016-08-07 08:48 UTC
Steps:
1. Open Microsoft Edge and go to https://www.websocket.org/echo.html 
2. Enter: wss://s.altnet.rippletest.net:51233
3. press Connect
4. JavaScript console logs the following error: WebSocket Error: Incorrect HTTP response. Status code 403, Forbidden

This works in Chrome. This also works if I use wss://s1.ripple.com:51233/

**Comment by mDuo13** [comment] 2016-09-02 00:10
I haven't found anyone on Windows to reproduce this, and there's no obvious config reason why that should be the case. Since it seems to work in every other browser, maybe it's just a bug in Edge?

**Comment by mDuo13** [comment] 2016-09-15 21:02
Update: this might be a bug in the WSS2 implementation of websockets, which doesn't return the right HTTP status code in some cases, or something like that. (I'm not fully appraised of the nature of the bug, but it was also causing 403s in some cases.) I think it's fixed in rippled v0.33.0, which should be out very soon.

In any case, this is not a dev-portal issue, so I'm closing this ticket, but thanks for bringing it to our attention.

**Closed as completed by mDuo13** 2016-09-15 21:02 UTC
