### ISSUE TITLE
Broken icons to external links in FAQ page.

### ISSUE THREAD

**Issue by tequdev** [XRPLF/xrpl-dev-portal#2085] opened 2023-08-23 13:56 UTC
Arrows Icons are shown too far up.

<img width="1119" alt="スクリーンショット 2023-08-23 22 55 14" src="https://github.com/XRPLF/xrpl-dev-portal/assets/69445828/48c43b5f-96ee-421c-8187-3c31c413c39f">

**Comment by DESMOND555** [comment] 2023-08-24 22:04
Hello  this is Desmond Kingsley, please I call for the assistance of to
respond to me please, I've been under some challenges for over 2 months now
please I plead to you to write to me on WhatsApp +2349136843896

**Comment by mDuo13** [comment] 2023-09-12 22:41
Assigned to @AKCodez because I suspect this was caused by #1925.

**Comment by AKCodez** [comment] 2023-09-13 17:40
Can anyone else replicate this? I cant seem to replicate it.

**Comment by mDuo13** [comment] 2024-07-12 21:40
This is no longer an issue on the current version of the site.

**Closed as completed by mDuo13** 2024-07-12 21:40 UTC
Labels: bug, web dev
