### ISSUE TITLE
Deprecated Ripple API is used

### ISSUE THREAD

**Issue by tequdev** [XRPLF/xrpl-dev-portal#1826] opened 2023-03-18 08:46 UTC
The deprecated RippleAPI is used in the following locations; it is recommended to replace it with a library such as xrpl.js.

https://xrpl.org/send-a-check.html#example-checkcreate-preparation
https://xrpl.org/look-up-checks-by-sender.html#example-request
https://xrpl.org/look-up-checks-by-recipient.html#example-request

**Comment by mDuo13** [comment] 2023-05-01 21:07
duplicate of #1206

**Closed as completed by mDuo13** 2023-05-01 21:07 UTC
