### ISSUE TITLE
Some images are hard to read

### ISSUE THREAD

**Issue by mvadari** [XRPLF/xrpl-dev-portal#1135] opened 2021-08-04 14:37 UTC
The image at https://xrpl.org/ledger-object-ids.html is basically impossible to read on the black background. I had to open the image in a new tab, where it opened against a white background, to be able to understand it.

I've seen this issue on one or two other pages as well, but I can't recall where exactly.

**Comment by mvadari** [comment] 2021-08-04 19:07
Another example: https://xrpl.org/paths.html

**Comment by mDuo13** [comment] 2021-09-22 20:15
This was a regression caused by a CSS change. Fixed now.

**Closed as completed by mDuo13** 2021-09-22 20:15 UTC
