### ISSUE TITLE
Idea: dedicated doc page for rippled.cfg

### ISSUE THREAD

**Issue by intelliot** [XRPLF/xrpl-dev-portal#1403] opened 2022-05-11 17:16 UTC
I've heard from multiple node operators that we could use additional documentation about rippled.cfg.

- Some existing documentation no longer matches the default config that ships with the rippled binary
- There isn't much documentation beyond the config example (rippled-example.cfg)
- The example config is confusing when you're trying to understand why different settings and node types exist

If such docs already exist, feel free to reply to this issue with some links

**Comment by mDuo13** [comment] 2022-05-17 00:53
Duplicate of #586

**Closed as completed by mDuo13** 2022-05-17 00:53 UTC
