### ISSUE TITLE
Docs: clarify that limit values below 10 will be set to 10, and values above 400 will be set to 400

### ISSUE THREAD

**Issue by intelliot** [XRPLF/xrpl-dev-portal#1985] opened 2023-06-29 22:38 UTC
- [account_channels](https://xrpl.org/account_channels.html#account_channels)
- [account_offers](https://xrpl.org/account_objects.html#account_objects)
- ledger_data
- account_nfts
- nft_sell_offers
- nft_buy_offers

Limit cannot be less than 10 or more than 400. Values outside the range are permitted, but are set to the min/max values. 

In other words: having a limit below 10 will auto set limit = 10, and above 400 will auto set limit = 400. The code had always been like this.

To prevent confusion, the docs should clarify that any `limit` outside of the range [10, 400] will be set to the min/max.

Ref: https://github.com/XRPLF/rippled/issues/4540

@mounikakun @PeterChen13579 @shawnxie999 @arihantkothari

**Comment by PeterChen13579** [comment] 2023-06-30 14:43
I believe we can also close [rippled#4541](https://github.com/XRPLF/rippled/issues/4541) and [rippled#4315](https://github.com/XRPLF/rippled/issues/4315) as well

**Comment by godexsoft** [comment] 2023-07-05 19:24
Let's not rush with this one. It looks like we may be going the other path: fix the issues on rippled side for api v2, leave the current behaviour for v1. 
Judging by the code, this would be an easier solution than fixing the doc and then introducing clamping in clio (currently returning errors as per docs).

**Comment by ximinez** [comment] 2023-07-06 15:47
> It looks like we may be going the other path: fix the issues on rippled side for api v2, leave the current behaviour for v1.

I disagree. IMHO, docs need to be clarified, not the code. In rippled-land, docs reflect the code, not the other way around, except in the case of a bug. This is not a bug - it's an intentional design decision. rippled request processing is and has always been "best effort", which means that it reserves the right to alter the request to protect it's own resources. Better to let rippled send one response with more or fewer results than requested than to have the client send a bunch of requests and get a bunch of errors trying to figure out the valid range because they haven't read the docs. It was my understanding that the design philosophy of clio was to follow the rippled API, which the docs attempt to describe, but are not always 100% accurate.

>  Judging by the code, this would be an easier solution than fixing the doc and then introducing clamping in clio (currently returning errors as per docs).

1. `limit = std::clamp(limit, lowlimit, highlimit);` The limits for each type of request are in src/ripple/rpc/impl/Tuning.h (which probably should be in a more "public" folder if/when we reorganize the code).
2. Unless I missed it, the docs don't say anything about out of range values returning an error. The two pages linked in this issue description say:
    > Limit the number of transactions to retrieve. Cannot be less than 10 or more than 400. The default is 200.
    
    and
    
    > The maximum number of objects to include in the results. Must be within the inclusive range 10 to 400 on non-admin connections. The default is 200.
    
    Nothing in there about an error. It's perfectly reasonable to interpret that as "Must be in this range. If not, rippled will alter your request." In fact, the response includes a `limit` field, which (I'm 99% sure) will reflect the value used, not the value requested. That's intentional.

**Comment by godexsoft** [comment] 2023-07-06 16:14
@ximinez I understand that rippled code was written before the docs but the docs do say "cannot be" so in clio we followed this advice combined with the error codes on that same page to deduce that the error should be `invalidParams`.
While we can adjust the docs and leave rippled be - it's currently much easier to fix on rippled side and leave the docs and clio as is. This is because in rippled each and every handler works directly on `json` and is responsible for parsing and validating the input. In clio we have a whole framework for just validation and parsing of json and we can't simply clamp the input thru that framework atm.
If you think it's really important that rippled remains as is then we can of course do it on clio side but that would not be preferred. Also @intelliot gave us green light on changing this in rippled and leaving docs alone. I'm open for discussion of course.

**Comment by ximinez** [comment] 2023-07-06 16:37
> it's currently much easier to fix on rippled side and leave the docs and clio as is.

My opinion is that easier is not always better or more correct. But now that I've said my piece, if the decision is to go ahead this way, I'll yield to the consensus opinion.

**Comment by godexsoft** [comment] 2023-07-07 13:36
Opinions may vary. Take a look at [this pr](https://github.com/XRPLF/clio/pull/740) when you have time. If we decide to mimic rippled for the `limit` field then this is one way to do it in clio.

**Comment by seelabs** [comment] 2023-07-07 14:42
Rippled's behavior seems reasonable to me here, and I strongly suspect the docs came after the implementation and were meant to document the code's behavior rather than specify the behavior. I'd be more inclined to change the doc rather than the behavior. Having said that, I think the factors here are:

1. Will this change break existing code
2. What behavior is most useful and least confusing to the user
3. How difficult is it to implement this behavior in rippled and clio

(1) I'm unsure, but I'd guess it's not too bad. (2) I prefer the rippled behavior, but returning an error is also reasonable. This is only a weak preference. (3) It should be easy to support either behavior in rippled or change the docs to reflect rippled's behavior. I don't know clio so I have no opinion there.

Anyway, just my $0.02.

**Comment by godexsoft** [comment] 2023-07-07 15:10
Thanks for your input @seelabs 👍 It's looking more and more like we will have to go with old rippled behaviour and just implement this on our end as well as update the docs. 

Clio can support clamping but it's a bit awkward (you can take a look at the pr i linked above for one possible implementation). 

I have almost no doubts that code came first and later the doc was written. The reason we have discrepancies however is because clio tried to follow the docs as close as possible without looking too much into rippled code. 
I think that was a mistake on our side to assume the docs exactly reflect rippled behaviour. 
That does not mean however that the docs should not reflect the reality exactly. In my opinion, ideally, a 3rd party implementor should be able to write their own "clio" server or a client library in say Rust just by looking at the docs.

**Comment by mDuo13** [comment] 2023-07-07 19:36
I think for some methods the docs even described the actual (clamping) behavior more specifically and then we updated the docs to be simpler to understand. IMO "cannot be less than 10 or more than 400" is consistent with the clamping behavior, although I could see why you would interpret that as triggering an invalidParams result instead.

**Comment by intelliot** [comment] 2023-07-08 06:04
English is ambiguous; code is not :) 

It's good to take a step back and consider how the API _should_ be designed, without considering what the current behavior is. That's what seelabs is getting at:

> What behavior is most useful and least confusing to the user

From this perspective, I believe clamping is the right thing to do. It's a more useful response than an error. It follows the [robustness principle](https://en.wikipedia.org/wiki/Robustness_principle). Other APIs (unrelated to rippled/Clio), like the GitHub API, have similar behavior. Some GitHub API endpoints support a parameter called `per_page`, which controls how many results are returned at once. It is clamped to 100. So if you specify 101 (or 200, or whatever), you will just get 100 items back. You get the same response as if you had specified 100 to begin with.

**Comment by godexsoft** [comment] 2023-07-10 15:11
Clamping support in clio merged in [this pr](https://github.com/XRPLF/clio/pull/740).
Will use it on `limit` fields in question. Let's update the doc.

**Comment by mDuo13** [comment] 2023-11-15 00:35
Fixed in #2008.

**Closed as completed by mDuo13** 2023-11-15 00:35 UTC
