### ISSUE TITLE
Make doc side menu stay with you as you scroll (on smaller browser sizes)

### ISSUE THREAD

**Issue by bugsbunnies** [XRPLF/xrpl-dev-portal#1444] opened 2022-07-30 00:01 UTC
Currently as you get to a smaller breakpoint (990px) on the browser, the documentation side menu disappears out of sight whenever you start scrolling. We should have it stick the left side as you scroll and also have the collapsable Page Toolbar menu stick to the top so it's always visible. 

<img width="963" alt="Screen Shot 2022-07-29 at 4 53 05 PM" src="https://user-images.githubusercontent.com/39572746/181861791-bec25dfe-e759-4960-baf9-adae53d146d3.png">
<img width="966" alt="Screen Shot 2022-07-29 at 4 52 51 PM" src="https://user-images.githubusercontent.com/39572746/181861794-a35b80a3-1007-43af-b4bb-ba6d3d1e9a91.png">

**Comment by mDuo13** [comment] 2022-08-02 00:13
Duplicate of #1311

**Closed as completed by mDuo13** 2022-08-02 00:13 UTC
