### ISSUE TITLE
build failed ,jinja2.exceptions.UndefinedError: No first item, sequence was empty.

### ISSUE THREAD

**Issue by maybeTomorrow** [XRPLF/xrpl-dev-portal#1150] opened 2021-08-20 03:43 UTC
Building page: <Page 'JavaScript / TypeScript Client Library' (rippleapi-reference.html)>
... markdown is ready
... parsing markdown...
... re-rendering HTML from soup...
Traceback (most recent call last):
  File "f:\program files\python3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "f:\program files\python3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "F:\Program Files\Python3\Scripts\dactyl_build.exe\__main__.py", line 7, in <module>
  File "f:\program files\python3\lib\site-packages\dactyl\dactyl_build.py", line 613, in dispatch_main
    main(cli.cli_args, config)
  File "f:\program files\python3\lib\site-packages\dactyl\dactyl_build.py", line 599, in main
    builder.build()
  File "f:\program files\python3\lib\site-packages\dactyl\dactyl_build.py", line 161, in build
    out_html = use_template.render(
  File "f:\program files\python3\lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "f:\program files\python3\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "tool\template-doc.html", line 1, in top-level template code
    {% extends "template-base.html" %}
  File "tool\template-base.html", line 101, in top-level template code
    {% block breadcrumbs %}
  File "tool\template-base.html", line 102, in block 'breadcrumbs'
    {% include 'breadcrumbs.html' %}
  File "f:\program files\python3\lib\site-packages\dactyl\templates\breadcrumbs.html", line 18, in top-level template code
    <li class="active breadcrumb-item"><a href="{% if "//" not in page.html %}{{ currentpage.prefix }}{% endif %}{{ page.html }}">{{ page.name }}</a></li>
jinja2.exceptions.UndefinedError: No first item, sequence was empty.

**Comment by mDuo13** [comment] 2021-09-14 22:31
Not sure what might cause this error; possibly an incompatibility in dependencies somewhere? Either that, or you have a typo in the config or something that's causing certain contents to not be loaded properly.

**Comment by mDuo13** [comment] 2021-10-04 23:04
Anyway, I'm unable to reproduce this issue with the repo as-is. If you want to provide additional context, please reopen and we can address that. For now, I'm going to close this.

**Closed as completed by mDuo13** 2021-10-04 23:04 UTC
